name: pluto
matrix:
  architectures:
    - amd64
    - arm64
  versions:
    - 5.15.1
    - 5.16.0
    - 5.16.1
    - 5.16.3
    - 5.16.4
    - 5.17.0
    - 5.18.0
    - 5.18.1
    - 5.18.2
    - 5.18.3
    - 5.18.4
    - 5.18.5
    - 5.18.6
homepage: https://github.com/FairwindsOps/pluto/
summary: discover deprecated apiversions in kubernetes
description: |-
  Pluto is a utility to help users find deprecated Kubernetes apiVersions in
  their code repositories and their helm releases.
fetch: https://github.com/FairwindsOps/pluto/releases/download/v{{version}}/pluto_{{version}}_linux_{{goarch}}.tar.gz
install:
  - pluto:/usr/bin/pluto
