site_name: WakeMeOps
site_url: https://docs.wakemeops.com
site_description: WakeMeOps documentation

repo_url: https://github.com/upciti/wakemeops
edit_uri: blob/main/docs/

nav:
  - Home: "index.md"
  - Usage: "usage.md"
  - Packages:
      - Dev: "components/dev.md"
      - Devops: "components/devops.md"
      - Secops: "components/secops.md"
      - Terminal: "components/terminal.md"
      - Desktop: "components/desktop.md"

theme:
  custom_dir: docs/theme_override_home/
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css
