site_name: WakeMeOps
site_url: https://docs.wakemeops.com/
site_description: WakeMeOps documentation

repo_url: https://github.com/upciti/wakemeops
edit_uri: ""

nav:
  - Home: "index.md"
  - Usage: "usage.md"
  - Packages:
      - Overview: "packages/index.md"
      - ...: "packages/template.md"
theme:
  custom_dir: docs/theme_override_home/
  name: "material"
  logo: "images/white-logo.png"
  favicon: "images/pink-logo.png"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    scheme: slate

plugins:
  - search
  - wakemedoc
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css
