- name: kompose
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
  version: 1.26.1
  homepage: https://kompose.io
  summary: convert docker-compose.yaml into k8s deployments and services
  description: |-
    kompose is a tool to help users who are familiar with docker-compose move to
    Kubernetes. kompose takes a Docker Compose file and translates it into
    Kubernetes resources.
  fetch: https://github.com/kubernetes/kompose/releases/download/v{{version}}/kompose-linux-{{goarch}}
  script:
    - mv kompose-linux-{{goarch}} {{src}}/usr/bin/kompose

- name: kompose
  matrix:
    architectures:
      - amd64
      - arm64
      - armhf
    versions:
      - 1.27.0
      - 1.28.0
      - 1.29.0
      - 1.30.0
      - 1.31.0
      - 1.31.1
      - 1.31.2
      - 1.32.0
      - 1.33.0
      - 1.34.0
  homepage: https://kompose.io
  summary: convert docker-compose.yaml into k8s deployments and services
  description: |-
    kompose is a tool to help users who are familiar with docker-compose move to
    Kubernetes. kompose takes a Docker Compose file and translates it into
    Kubernetes resources.
  fetch: https://github.com/kubernetes/kompose/releases/download/v{{version}}/kompose-linux-{{goarch}}
  install:
    - kompose-linux-{{goarch}}:/usr/bin/kompose
