name: krr
matrix:
  architectures:
    - amd64
version: 1.6.0
homepage: https://github.com/robusta-dev/krr
summary: Prometheus-based Kubernetes Resource Recommendations
description: |-
  Robusta KRR (Kubernetes Resource Recommender) is a CLI tool for optimizing
  resource allocation in Kubernetes clusters. It gathers pod usage data from
  Prometheus and recommends requests and limits for CPU and memory. This reduces
  costs and improves performance.
fetch: https://github.com/robusta-dev/krr/releases/download/v1.6.0/krr-ubuntu-latest-v1.6.0.zip
install:
  - krr:/usr/lib/krr
script:
  - ln -s /usr/lib/krr/krr {{src}}/usr/bin/krr
  - chmod +x {{src}}/usr/lib/krr/krr
