name: ✨ Publish packages

on:
  push:
    branches:
      - main

jobs:
  build_packages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/upciti/ops2deb:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print ops2deb version
        run: ops2deb version

      - name: Generate new Debian packages
        run: |
          make generate
          make build

      - name: Upload Debian packages
        uses: actions/upload-artifact@v3
        with:
          path: build/**/*deb
          retention-days: 2

  publish_packages:
    needs: [build_packages]
    runs-on: ubuntu-latest
    container:
      image: upciti/wakemebot:latest
    steps:
      - name: Print wakemebot version
        run: wakemebot version

      - name: Download Debian packages
        uses: actions/download-artifact@v3

      - name: Upload Debian packages
        working-directory: artifact
        shell: bash
        run: |
          for i in $(ls build); do wakemebot aptly push wakemeops-$i build/$i; done

      - name: Publish repository
        run: |
          wakemebot aptly publish s3:wakemeops-eu-west-3:wakemeops/stable
