name: ✨ Publish packages

on:
  push:
    branches:
      - main

jobs:
  build_packages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/upciti/ops2deb:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print ops2deb version
        run: ops2deb version

      - name: Generate new Debian packages
        run: |
          make build

      - name: Upload Debian packages
        uses: actions/upload-artifact@v3
        with:
          path: build/**/*deb
          retention-days: 2

  publish_packages:
    needs: [build_packages]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/upciti/wakemebot:4
    steps:
      - name: Print wakemebot version
        run: wakemebot version

      - name: Download Debian packages
        uses: actions/download-artifact@v3

      - name: Upload Debian packages
        shell: bash
        env:
          WAKEMEBOT_APTLY_SERVER_URL: ${{ secrets.WAKEMEBOT_APTLY_SERVER_URL }}
          WAKEMEBOT_APTLY_CA_CERT: ${{ secrets.WAKEMEBOT_APTLY_CA_CERT }}
          WAKEMEBOT_APTLY_CLIENT_CERT: ${{ secrets.WAKEMEBOT_APTLY_CLIENT_CERT }}
          WAKEMEBOT_APTLY_CLIENT_KEY: ${{ secrets.WAKEMEBOT_APTLY_CLIENT_KEY }}
        run: |
          ls -lah
          for i in $(ls artifact); do wakemebot aptly push wakemeops-$i artifact/$i; done
          wakemebot aptly publish s3:wakemeops-eu-west-3:wakemeops/stable
