name: bank-vaults
matrix:
  versions:
    - 1.15.1
    - 1.15.2
  architectures:
    - amd64
    - arm64
homepage: https://banzaicloud.com/products/bank-vaults/
summary: make using and operating Hashicorp Vault easier on Kubernetes.
description: |-
  Bank Vaults is a thick, tricky, shifty right with a fast and intense tube for
  experienced surfers only, located on Mentawai. Think heavy steel doors, secret
  unlocking combinations and burly guards with smack-down attitude. Watch out for
  clean-up sets.
fetch: https://github.com/banzaicloud/bank-vaults/releases/download/{{version}}/bank-vaults-linux-{{goarch}}.tar.gz
install:
  - bank-vaults:/usr/bin/
